# Generated by Django 2.2.15 on 2020-09-24 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='品牌')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='供应商')),
                ('tel', models.CharField(blank=True, max_length=256, null=True, verbose_name='优势品牌')),
                ('contact', models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='联系手机')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='Model_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk_model', models.CharField(max_length=32, verbose_name='公司型号')),
                ('sp_model', models.CharField(max_length=32, verbose_name='供应商型号')),
                ('meno', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '型号登记',
                'verbose_name_plural': '型号登记',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='标题')),
                ('details', mdeditor.fields.MDTextField(verbose_name='详情')),
                ('date', models.DateField(auto_now=True, verbose_name='更改日期')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
            ],
            options={
                'verbose_name': '经验',
                'verbose_name_plural': '经验',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gmodel', models.CharField(max_length=64, unique=True, verbose_name='品名规格')),
                ('unit', models.IntegerField(choices=[(0, '台'), (1, '支'), (2, '个'), (3, '站点'), (4, '用户'), (5, '套'), (6, '平方'), (7, '卷'), (8, '根'), (9, 'PCS')], default=0, verbose_name='单位')),
                ('type', models.IntegerField(choices=[(0, '条码打印机'), (1, '条码扫描器'), (2, '数据终端'), (3, '软件'), (4, '配件'), (5, '耗材'), (6, 'RFID设备'), (7, '其它')], default=0, verbose_name='分类')),
                ('price', models.FloatField(default=0, verbose_name='产品进价')),
                ('min_price', models.FloatField(default=0, verbose_name='最低售价')),
                ('meno', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('date', models.DateField(auto_now=True, verbose_name='更改日期')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Brand', verbose_name='品牌')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Supplier', verbose_name='供应商')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品信息',
            },
        ),
    ]
