# Generated by Django 2.2.15 on 2020-09-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='meno',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='备注'),
        ),
    ]
